package request

// Sale is a Sale the till asks the server to record as an Order. The till
// only previews money and Stock; the server prices each Line and draws its
// Stock itself (see app/domain/sale).
type Sale struct {
	// SaleId is generated by the till once per Sale; recording the same Sale
	// again returns the Order already recorded.
	SaleId         string         `json:"saleId" binding:"required,max=64"`
	Items          []SaleLine     `json:"items" binding:"required,min=1,dive"`
	Payments       []OrderPayment `json:"payments" binding:"required,min=1,dive"`
	Type           string         `json:"type" binding:"required"`
	CustomerCode   string         `json:"customerCode"`
	CustomerName   string         `json:"customerName"`
	PatientId      string         `json:"patientId"`
	PharmacistName string         `json:"pharmacistName"`
	LicenseNo      string         `json:"licenseNo"`
	PrescriberName string         `json:"prescriberName"`
	BuyerName      string         `json:"buyerName"`
	BuyerIdCard    string         `json:"buyerIdCard"`
	Message        string         `json:"message"`
	CreatedBy      string         `json:"-"`
	Code           string         `json:"-"`
	BranchId       string         `json:"-"`
}

type SaleLine struct {
	ProductId string `json:"productId" binding:"required"`
	UnitId    string `json:"unitId" binding:"required"`
	Quantity  int    `json:"quantity" binding:"required,gt=0"`
	// PriceType is the Customer type's price list, or "Stock".
	PriceType string `json:"priceType"`
	// StockId is a Stock the cashier chose to sell from first.
	StockId       string  `json:"stockId"`
	Discount      float64 `json:"discount"` // per unit
	AllowOversell bool    `json:"allowOversell"`
}
