package constant

const (
	MEMBER         = "MEMBER"
	ORDER          = "ORDER"
	RECEIVE        = "RECEIVE"
	PRODUCT        = "PRODUCT"
	BRANCH         = "BRANCH"
	EMPLOYEE       = "EMPLOYEE"
	PURCHASE_ORDER = "PURCHASE_ORDER"
	DELIVERY_ORDER = "DELIVERY_ORDER"
	CREDIT_NOTE    = "CREDIT_NOTE"
	BILLING        = "BILLING"
	QUOTATION      = "QUOTATION"
	STOCK_TRANSFER = "STOCK_TRANSFER"
)

const (
	DAILY   = "DAILY"
	MONTHLY = "MONTHLY"
	YEARLY  = "YEARLY"
	NONE    = "NONE"
)
