package constant

const (
	MEMBER           = "MEMBER"
	ORDER            = "ORDER"
	RECEIVE          = "RECEIVE"
	PRODUCT          = "PRODUCT"
	BRANCH           = "BRANCH"
	EMPLOYEE         = "EMPLOYEE"
	STOCK_TRANSFER   = "STOCK_TRANSFER"
	STOCK_ADJUSTMENT = "STOCK_ADJUSTMENT"
	STOCK_COUNT      = "STOCK_COUNT"
	PRODUCT_RETURN   = "PRODUCT_RETURN"
)

const (
	DAILY   = "DAILY"
	MONTHLY = "MONTHLY"
	YEARLY  = "YEARLY"
	NONE    = "NONE"
)
